dist: bionic

language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

addons:
  apt:
    packages:
      - libpcap-dev
      - swig

branches:
  only:
  - master

notifications:
  email:
    recipients:
    - zeek-commits-internal@zeek.org

before_install:
  # Clone the zeek git repo and replace zeekctl.
  - cd ..
  - tar cf zeekctl.tar --exclude=.git zeekctl
  - rm -rf zeekctl
  - git clone --recursive https://github.com/zeek/zeek zeek
  - rm -rf zeek/auxil/zeekctl
  - tar xf zeekctl.tar -C zeek/auxil
  - rm -f zeekctl.tar
  - cd zeek/auxil/zeekctl/testing

install:
  - make buildzeek

script: ../../btest/btest -f diag.log -A

after_failure: cat diag.log
