# LGTM config file docs: https://lgtm.com/help/lgtm/lgtm.yml-configuration-file

# Results from files under any classifier will be excluded from LGTM stats.
path_classifiers:
  library:
    - "caf"
    - "3rdparty"

# Filter out alerts that aren't concerning.
queries:
  - exclude: cpp/use-of-goto

extraction:
  cpp:
    prepare:
      # Ubuntu packages to install.
      packages:
        - cmake
        - make
        - ninja-build
        - gcc-8
        - g++-8
        - libssl-dev
        - python3
        - python3-dev

    configure:
      command:
        - ./configure --build-type=debug --generator=Ninja --enable-static

    index:
      build_command:
        - ( cd build && ninja )
